name: datos_faltantes # Puedes cambiar este nombre por uno de tu preferencia
channels:
  - conda-forge # Un canal común donde se encuentran muchas de estas librerías
  - defaults  # El canal por defecto de anaconda/miniconda
dependencies:
  # Asegúrate de tener Python
  - python=3.9 # O la versión de Python que necesites

  # Paquete necesario para crear el kernel de Jupyter
  - ipykernel

  # Librerías de tu requirements.txt, especificando versiones donde sea necesario
  # Intentamos instalarlas con conda/mamba si están disponibles
  - pyjanitor
  - missingno
  - numpy=1.24.4
  - matplotlib=3.5.1
  - pandas
  - pyreadr
  - seaborn
  - session-info
  - upsetplot=0.6.1

  # Si alguna de las librerías anteriores no se encontrara en los canales de conda/mamba,
  # o si prefieres asegurarte de usar pip para alguna, podrías usar la sección pip:
  # - pip:
  #   - nombre_de_la_libreria # Descomenta y añade aquí si es necesario
  #   - otra_libreria==X.Y
