name: datos_faltantes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - pyjanitor
  - missingno
  - numpy=1.24.4
  - matplotlib=3.5.1
  - pandas
  - pyreadr
  - seaborn
  - session-info
  - upsetplot=0.6.1
  - kaggle
  # Aquí ya NO va pyfilesystem2 si vas a usar pathlib
  # pathlib es parte de la librería estándar de Python, no necesita ser listada como dependencia externa
